config/routes.rb
Gambling::Application.routes.draw do
  # Concerns
  concern :loggable do |options|
    resources :logs, only: [:index], module: options[:module] do
      collection do
        get :change
      end
    end
  end

  devise_for :agents, path: :my, skip: [:registrations, :passwords, :confirmations]
  devise_scope :agent do
    resource :registration, only: [:edit, :update],
      path: :my,
      path_names: { edit: 'edit' },
      controller: 'my/registrations',
      as: :agent_registration
  end

  devise_for :agent_sub_accounts, path: :sub_account, skip: [:registrations, :passwords, :confirmations]
  devise_scope :agent_sub_account do
    resource :registration, only: [:edit, :update],
      path: :sub_account,
      path_names: { edit: 'edit' },
      controller: 'devise/registrations',
      as: :agent_sub_account_registration
  end

  # 1. 主畫面
  root 'dashboard#index'

  namespace :dashboard do
    get :site_map
  end

  # 2. 代理階層
  namespace :agent do
    resource :levels, only: :show
  end

  resources :finances, only: :index
  resources :commissions, only: [:index, :show] do 
    get :users, on: :collection
    get :details, on: :collection
  end

  resources :logs, only: :index

  namespace :log do
    resources :agent_withdraws, only: [:index, :show]
  end
  
  # 玩家提款處理
  resources :withdraws, only: [:index, :show, :update, :destroy]

  namespace :withdraw do
    # 代理買分
    resources :agent_deposits, only: [:new, :create] do
      get :autocomplete_agent_username, on: :collection
    end
    resources :agent_cashouts, only: [:new, :create] do
      get :autocomplete_agent_username, on: :collection
    end
    resources :agent_withdraws, only: [:index, :show]
  end

  # 3. 代理階層
  resources :agents, only: [:edit, :update, :index, :show] do
    # a. 玩家
    resources :users, only: [:index, :new, :create], module: :agent
    # b. 子經銷
    resources :childs, only: [:index, :new, :create], module: :agent
    # c. 機器
    resources :machines, only: :index, module: :agent
    # d. 財務
    resources :finances, only: :index, module: :agent do
      get :export, on: :collection
    end
    # e. logger
    concerns :loggable, module: :agent
    # f. 結帳
    resources :cashouts, only: [:create], module: :agent
    # g. 鎖定
    resource :locks, only: [:create, :destroy], module: :agent do
      get :destroy_confirm
      get :parent_lock_notice
    end
    # 充提報表
    resources :withdraws, only: :index, module: :agent
    # 產生推薦碼
    resource :recommend_codes, only: :create, module: :agent
    # finances select 取得下層
    get :get_children
  end

  # 4. 玩家管理
  resources :users, only: [:edit, :update, :index, :show, :new, :create] do
    get :limit_table, on: :collection
    get :logs, module: :user, on: :collection
    get "transfer_credit" => :transfer_credit
    resources :deposits, only: [:new, :create], module: :user
    resources :cashouts, only: [:new, :create], module: :user
    resources :details, only: :index, module: :user
  end

  # 5. 子帳號管理
  resources :accounts, except: [:show, :destory] do
    resource :locks, only: [:create, :destroy], module: :account
    concerns :loggable, module: :account
  end

  # 6. 機器管理
  resources :machines, only: [:index, :show, :destroy] do
    resources :cashouts, only: [:new, :create], module: :machine do
      get :withdraw, on: :collection
    end
    get :logs, module: :machine, on: :collection
    resources :deposits, only: [:new, :create], module: :machine
    resource :controls, only: [:create, :destroy], module: :machine
    concerns :loggable, module: :machine
  end

  # 7. 維護模式
  resource :maintains, only: [:new, :create, :destroy], module: :machine, on: :collection

  # 8. Pusher 認證
  resource :channels, only: :create

  # 9. 遊戲歷程
  namespace :histories do
    # resources :main, only: :index do
    #   get :export, on: :collection
    # end
    # resources :slot, only: :index do
    #   get :export, on: :collection
    # end
    # resources :little_mary, only: :index do
    #   get :export, on: :collection
    # end
    # resources :racing, only: [:index, :show] do
    #   get :export, on: :collection
    # end
    # resources :poker, only: [:index, :show] do
    #   get :export, on: :collection
    # end
    # resources :fishing_joy, only: [:index, :show] do
    #   get :export, on: :collection
    # end
    # resources :roulette, only: [:index, :show] do
    #   get :export, on: :collection
    # end
    resources :game, only: [:index, :show] do
      get :export, on: :collection
      get :game_result, on: :collection
    end
    # resources :electronic_game, only: [:index, :show] do
    #   get :export, on: :collection
    # end
  end

  # 10. 場次
  namespace :schedules do
    resources :racings, only: :index
  end

  # 最新公告
  resources :news, only: [:index, :show]
end

app/controllers/histories/base_controller.rb
class Histories::BaseController < ApplicationController
  include DateRangeFilter
  before_action :valid_permission!, :set_agent_breadcrumbs_path, :set_default_date_range, :set_bet_forms
  before_action :set_breadcrumb, only: :index

  def index
    @bet_forms = @bet_forms.page(params[:page])
    @role_search_params = role_search_params
  end

  def export
    respond_to do |format|
      format.xlsx {
        render xlsx: "export", filename: "#{Setting.title}-#{params[:controller]}-(#{@begin_date}_to_#{@end_date}).xlsx"
      }
    end
  end

  protected

  def set_agent_breadcrumbs_path
    drop_breadcrumb(t('breadcrumbs.history'), histories_game_index_path)
  end

  def valid_permission!
    authorize :history, :all?
  end

  def valid_not_shop_site!
    render_404! if Setting.shop_site?
  end

  def valid_cash_site!
    render_404! unless Setting.cash_site?
  end
end

app/controllers/histories/electronic_game_controller.rb
class Histories::ElectronicGameController < Histories::BaseController
  include ApplicationHelper

  private

  def set_breadcrumb
    drop_breadcrumb(t('breadcrumbs.histories.electronic_game'))
  end

  def set_bet_forms
    @bet_forms = current_agent.all_electronic_bet_forms.where(role_search_params).date_range(@begin_date, @end_date).includes(:user, :agent, :director, :shareholder)
  end

  def role_search_params
    params[:role].present? ? params.require(:role).permit(:agent_id, :user_id, :shareholder_id, :director_id) : {}
  end
end

app/controllers/histories/fishing_joy_controller.rb
class Histories::FishingJoyController < Histories::BaseController
  before_action :valid_not_shop_site!

  private

  def set_breadcrumb
    drop_breadcrumb(t('breadcrumbs.histories.fishing_joy'))
  end

  def set_bet_forms
    @bet_forms = current_agent.all_fishing_joy_bet_forms.where(role_search_params).date_range(@begin_date, @end_date).includes(:user, :agent, :director, :shareholder)
  end

  def role_search_params
    if params[:role].present?
      params.require(:role).permit(:agent_id, :shareholder_id, :director_id, :user_id)
    else
      {}
    end
  end
end

app/controllers/histories/game_controller.rb
class Histories::GameController < Histories::BaseController

  def index
    @sum = @bet_forms.histories_sum.first
    @bet_forms = @bet_forms.page(params[:page])
    super
  end

  def game_result
    bet_form_id = params[:bet_form_id]
    bet_form = ThirdPartyBetForm.find(bet_form_id)
    @platform_name = bet_form.game_platform.name
    platform = GamePlatforms::User.new(@platform_name, User.find(bet_form.user_id))

    @game_data = platform.game_result(bet_form)

    respond_to do |format|
      format.js
    end
  end

  private

  def set_breadcrumb
    drop_breadcrumb(t('breadcrumbs.histories.game'))
  end

  def set_bet_forms
    @type = params[:type] || 'all'
    @category_id = params[:category]
    @platform = GamePlatform.find_by_name(@type)
    @bet_forms = current_agent.all_third_party_bet_forms.where(role_search_params).date_range(@begin_date, @end_date).includes(:user, :agent, :director, :shareholder)
    @bet_forms = @bet_forms.where(game_platform: @platform) unless @type == 'all'
    @bet_forms = @bet_forms.category(@type, params[:category].to_i) if @category_id.present?
  end

  def role_search_params
    params[:role].present? ? params.require(:role).permit(:agent_id, :user_id, :shareholder_id, :director_id, :slot_machine_id) : {}
  end
end

app/controllers/histories/little_mary_controller.rb
class Histories::LittleMaryController < Histories::BaseController
  before_action :valid_not_shop_site!

  private

  def set_breadcrumb
    drop_breadcrumb(t('breadcrumbs.histories.little_mary'))
  end

  def set_bet_forms
    @bet_forms = current_agent.all_little_mary_bet_forms.where(role_search_params).date_range(@begin_date, @end_date).includes(:user, :agent, :director, :shareholder)
  end

  def role_search_params
    if params[:role].present?
      params.require(:role).permit(:agent_id, :shareholder_id, :director_id, :user_id)
    else
      {}
    end
  end
end

app/controllers/histories/main_controller.rb
class Histories::MainController < Histories::SlotController
    def index
      data = {type: params[:type], begin_date: params[:begin_date], end_date: params[:end_date], role: params[:role]}
      case params[:type]
      when 'little_mary'
        redirect_to histories_little_mary_index_url(data)
      when 'poker'
        redirect_to histories_poker_index_url(data)
      when 'roulette'
        redirect_to histories_roulette_index_url(data)
      when 'fishing_joy'
        redirect_to histories_fishing_joy_index_url(data)
      else
        # redirect_to histories_slot_index_url(data)
        redirect_to histories_game_index_url(data)
      end
    end
end

app/controllers/histories/poker_controller.rb
class Histories::PokerController < Histories::BaseController
  before_action :valid_not_shop_site!

  private

  def set_breadcrumb
    drop_breadcrumb(t('breadcrumbs.histories.poker'))
  end

  def set_bet_forms
    @bet_forms = current_agent.all_poker_bet_forms.where(role_search_params).date_range(@begin_date, @end_date).includes(:user, :agent, :director, :shareholder)
  end

  def role_search_params
    if params[:role].present?
      params.require(:role).permit(:agent_id, :shareholder_id, :director_id, :user_id)
    else
      {}
    end
  end
end

app/controllers/histories/racing_controller.rb
class Histories::RacingController < Histories::BaseController

  # GET histories/racings/1.js
  def show
    respond_to do |format|
      format.js {
        @racing_bet_form = current_agent.all_racing_bet_forms.find(params[:id])
        @sub_bet_forms = @racing_bet_form.racing_sub_bet_forms
      }
    end
  end

  private

  def set_breadcrumb
    drop_breadcrumb(t('breadcrumbs.histories.racing'))
  end

  def set_bet_forms
    @bet_forms = current_agent.all_racing_bet_forms.where(role_search_params).date_range(@begin_date, @end_date).includes(:user, :agent, :director, :shareholder)
  end

  def role_search_params
    if params[:role].present?
      params.require(:role).permit(:agent_id, :machine_id, :shareholder_id, :director_id, :racing_schedule_id)
    else
      {}
    end
  end
end

app/controllers/histories/roulette_controller.rb
class Histories::RouletteController < Histories::BaseController
  before_action :valid_not_shop_site!

  private

  def set_breadcrumb
    drop_breadcrumb(t('breadcrumbs.histories.roulette'))
  end

  def set_bet_forms
    @bet_forms = current_agent.all_roulette_bet_forms.where(role_search_params).date_range(@begin_date, @end_date).includes(:user, :agent, :director, :shareholder)
  end

  def role_search_params
    if params[:role].present?
      params.require(:role).permit(:agent_id, :shareholder_id, :director_id, :user_id)
    else
      {}
    end
  end
end

app/controllers/histories/slot_controller.rb
class Histories::SlotController < Histories::BaseController

  def index
    data = {type: params[:type], begin_date: params[:begin_date], end_date: params[:end_date], role: params[:role]}
    redirect_to histories_game_index_url(data)
  end

  private

  def set_breadcrumb
    drop_breadcrumb(t('breadcrumbs.histories.slot'))
  end

  def set_bet_forms
    @bet_forms = current_agent.all_slot_bet_forms.where(role_search_params).date_range(@begin_date, @end_date).includes(:user, :agent, :director, :shareholder)
  end

  def role_search_params
    if params[:role].present?
      params.require(:role).permit(:agent_id, :machine_id, :shareholder_id, :director_id, :user_id)
    else
      {}
    end
  end
end

app/controllers/schedules/racings_controller.rb
class Schedules::RacingsController < Schedules::BaseController
  before_action :set_agent_breadcrumbs_path

  def index
    @racing_schedules = RacingSchedule.page(params[:page])
  end
end

app/views/histories/racing/_racing_bet_form.html.haml
- cache [racing_bet_form, current_agent] do
  = content_tag_for(:tr, racing_bet_form) do
    - if racing_bet_form.user.nil?
      %td= link_to(racing_bet_form.agent.username, racing_bet_form.machine.agent, class: 'font-gary')
      %td= link_to(racing_bet_form.machine.title, machine_path(racing_bet_form.machine, format: :js), method: :get, remote: :true, class: racing_bet_form.machine.deleted? ? 'font-disable' : 'font-gary')
    - else
      %td= link_to(racing_bet_form.agent.username, racing_bet_form.user.agent, class: 'font-gary')
      %td= link_to(racing_bet_form.user.title, user_path(racing_bet_form.user), method: :get, class: 'font-gary')
    - if greater_shareholder_level(current_agent)
      %td.right= currency_format(racing_bet_form.shareholder_win_amount)
    - if greater_director_level(current_agent)
      %td.right= currency_format(racing_bet_form.director_win_amount)
    - if greater_agent_level(current_agent)
      %td.right= currency_format(racing_bet_form.agent_win_amount)
    %td.right= default_currency(racing_bet_form.bet_total_credit)
    %td.right= link_to(racing_bet_form.racing_sub_bet_forms.size, histories_racing_path(racing_bet_form, format: :js), method: :get, remote: :true, class: 'font-gary')
    %td.right= bonus_currency(racing_bet_form.reward_amount)
    %td.right= default_log_time(racing_bet_form.created_at)

app/views/histories/racing/_racing_sub_bet_forms.html.haml
- player = @racing_bet_form.machine.nil? ? @racing_bet_form.user : @racing_bet_form.machine
#sub_bet_forms.modal.fade{tabindex: -1,role: 'dialog', aria: {labelledby: 'modal', hidden: 'true'}}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: {dismiss: 'modal'}}
          .fa.fa-times
        %span.modal-title.font-md= "#{player.title} - #{t('.sub_bet_forms_detail')}"
      .modal-body
        .table-responsive
          %table.table
            %thead
              %tr.active
                %th.left{width: 75}= t('.bet_credit')
                %th.center{data: {priority: '3'}}= t('.bet_type')
                %th.center= t('.bet_number')
                %th.right{data: {priority: '3'}}= t('.odds')
                %th.right= t('.reward_amount')
            %tbody
              - if @sub_bet_forms.empty?
                %tr
                  %td{colspan: 2}= t('shared.no_data')
              - @sub_bet_forms.each do |sub_bet_form|
                %tr
                  %td.right= default_currency(sub_bet_form.bet_credit)
                  %td.center= sub_bet_form.bet_type
                  %td.center= sub_bet_form.bet_number
                  %td.right= sub_bet_form.odds
                  %td.right= bonus_currency(sub_bet_form.reward_amount)
      .modal-footer
        %button.btn.btn-default.pull-right{data: {dismiss: 'modal'}}= t('btn.close')

app/views/histories/racing/index.html.haml
= render 'histories/filter_bar', type: 'racing'
.table-responsive
  %table.table.table-valign-middle.table-font-sm.table-hover
    %thead
      %tr.success
        %th{width: 80, data: {priority: '6'}}= t('.shop')
        %th= t('.player')
        - if greater_shareholder_level(current_agent)
          %th.right{width: 80}= t('.shareholder_win_amount')
        - if greater_director_level(current_agent)
          %th.right{width: 80}= t('.director_win_amount')
        - if greater_agent_level(current_agent)
          %th.right{width: 80}= t('.agent_win_amount')
        %th.right{width: 130, data: {priority: '3'}}= t('.bet_total_credit')
        %th.right{width: 70, data: {priority: '3'}}= t('.bet_count')
        %th.right{width: 70, data: {priority: '3'}}= t('.reward_amount')
        %th.center{width: 130}= t('.created_at')
    - if @bet_forms.empty?
      %tr
        %td{colspan: 6}= t('shared.no_data')
    = render partial: 'racing_bet_form', collection: @bet_forms
= will_paginate(@bet_forms)

app/views/histories/racing/show.js.erb
(function(){
  $sub_bet_forms = $("<%=j render 'racing_sub_bet_forms' %>");
  if ($('#sub_bet_forms').size() > 0) {
    $('#sub_bet_forms').html($sub_bet_forms.html());
  } else {
    $('body').append($sub_bet_forms);
  }
  $('#sub_bet_forms').modal();
})();