config/routes.rb
Gambling::Application.routes.draw do
  # Concerns
  concern :loggable do |options|
    resources :logs, only: [:index], module: options[:module] do
      collection do
        get :change
      end
    end
  end

  devise_for :agents, path: :my, skip: [:registrations, :passwords, :confirmations]
  devise_scope :agent do
    resource :registration, only: [:edit, :update],
      path: :my,
      path_names: { edit: 'edit' },
      controller: 'my/registrations',
      as: :agent_registration
  end

  devise_for :agent_sub_accounts, path: :sub_account, skip: [:registrations, :passwords, :confirmations]
  devise_scope :agent_sub_account do
    resource :registration, only: [:edit, :update],
      path: :sub_account,
      path_names: { edit: 'edit' },
      controller: 'devise/registrations',
      as: :agent_sub_account_registration
  end

  # 1. 主畫面
  root 'dashboard#index'

  namespace :dashboard do
    get :site_map
  end

  # 2. 代理階層
  namespace :agent do
    resource :levels, only: :show
  end

  resources :finances, only: :index
  resources :commissions, only: [:index, :show] do 
    get :users, on: :collection
    get :details, on: :collection
  end

  resources :logs, only: :index

  namespace :log do
    resources :agent_withdraws, only: [:index, :show]
  end
  
  # 玩家提款處理
  resources :withdraws, only: [:index, :show, :update, :destroy]

  namespace :withdraw do
    # 代理買分
    resources :agent_deposits, only: [:new, :create] do
      get :autocomplete_agent_username, on: :collection
    end
    resources :agent_cashouts, only: [:new, :create] do
      get :autocomplete_agent_username, on: :collection
    end
    resources :agent_withdraws, only: [:index, :show]
  end

  # 3. 代理階層
  resources :agents, only: [:edit, :update, :index, :show] do
    # a. 玩家
    resources :users, only: [:index, :new, :create], module: :agent
    # b. 子經銷
    resources :childs, only: [:index, :new, :create], module: :agent
    # c. 機器
    resources :machines, only: :index, module: :agent
    # d. 財務
    resources :finances, only: :index, module: :agent do
      get :export, on: :collection
    end
    # e. logger
    concerns :loggable, module: :agent
    # f. 結帳
    resources :cashouts, only: [:create], module: :agent
    # g. 鎖定
    resource :locks, only: [:create, :destroy], module: :agent do
      get :destroy_confirm
      get :parent_lock_notice
    end
    # 充提報表
    resources :withdraws, only: :index, module: :agent
    # 產生推薦碼
    resource :recommend_codes, only: :create, module: :agent
    # finances select 取得下層
    get :get_children
  end

  # 4. 玩家管理
  resources :users, only: [:edit, :update, :index, :show, :new, :create] do
    get :limit_table, on: :collection
    get :logs, module: :user, on: :collection
    get "transfer_credit" => :transfer_credit
    resources :deposits, only: [:new, :create], module: :user
    resources :cashouts, only: [:new, :create], module: :user
    resources :details, only: :index, module: :user
  end

  # 5. 子帳號管理
  resources :accounts, except: [:show, :destory] do
    resource :locks, only: [:create, :destroy], module: :account
    concerns :loggable, module: :account
  end

  # 6. 機器管理
  resources :machines, only: [:index, :show, :destroy] do
    resources :cashouts, only: [:new, :create], module: :machine do
      get :withdraw, on: :collection
    end
    get :logs, module: :machine, on: :collection
    resources :deposits, only: [:new, :create], module: :machine
    resource :controls, only: [:create, :destroy], module: :machine
    concerns :loggable, module: :machine
  end

  # 7. 維護模式
  resource :maintains, only: [:new, :create, :destroy], module: :machine, on: :collection

  # 8. Pusher 認證
  resource :channels, only: :create

  # 9. 遊戲歷程
  namespace :histories do
    # resources :main, only: :index do
    #   get :export, on: :collection
    # end
    # resources :slot, only: :index do
    #   get :export, on: :collection
    # end
    # resources :little_mary, only: :index do
    #   get :export, on: :collection
    # end
    # resources :racing, only: [:index, :show] do
    #   get :export, on: :collection
    # end
    # resources :poker, only: [:index, :show] do
    #   get :export, on: :collection
    # end
    # resources :fishing_joy, only: [:index, :show] do
    #   get :export, on: :collection
    # end
    # resources :roulette, only: [:index, :show] do
    #   get :export, on: :collection
    # end
    resources :game, only: [:index, :show] do
      get :export, on: :collection
      get :game_result, on: :collection
    end
    # resources :electronic_game, only: [:index, :show] do
    #   get :export, on: :collection
    # end
  end

  # 10. 場次
  namespace :schedules do
    resources :racings, only: :index
  end

  # 最新公告
  resources :news, only: [:index, :show]
end

app/controllers/agent/withdraws_controller.rb
class Agent::WithdrawsController < Agent::BaseController
  include DateRangeFilter
  before_action :set_agent
  before_action :valid_permission!, :set_default_date_range

  # GET /agent/withdraws
  def index
    drop_breadcrumb(t('breadcrumbs.reports.withdraw.agent', agent: @agent.title), agent_withdraws_path(@agent))

    @withdraw_stats, @withdraw_total = Withdraw::ChildrenReport.call(begin_date: @begin_date, end_date: @end_date, agent: @agent)

    render 'reports/withdraws/index'
  end

  protected

  def valid_permission!
    authorize :report, :all?
  end
end

app/controllers/withdraw/agent_cashouts_controller.rb
class Withdraw::AgentCashoutsController < Withdraw::BaseController
  before_action :set_withdraw
  autocomplete :user, :username
  # GET /agent_withdraw/:cashouts/new
  def new; end

  def create
    if @withdraw.cashout
      @withdraw.agent.create_log(:cashout, current_agent, remote_ip ,points: @withdraw.points.to_f, agent_withdraw_id: @withdraw.model.id, trade_no: @withdraw.model.trade_no, status: 'transferred')
      unless @withdraw.agent.parent.nil?
        @withdraw.agent.parent.create_log(:refund, current_agent, remote_ip ,points: @withdraw.points.to_f, agent_withdraw_id: @withdraw.refund_model.id, trade_no: @withdraw.refund_model.trade_no, status: 'transferred', related_agent_withdraw_id: @withdraw.model.id)
      end
      redirect_to new_withdraw_agent_cashout_path, notice: t('flash.agent_withdraw.cashouts.finish')
    else
      render :new
    end
  end

  def autocomplete_agent_username
    term = params[:term]
    agents = current_agent.children.where('username LIKE ?', "%#{term}%").where(type_cd: 1).order(:username).all
    render :json => agents.map { |agent| {:id => agent.id, :label => agent.username, :value => agent.username} }
  end

  protected

  def set_breadcrumbs
    drop_breadcrumb(t('breadcrumbs.agent_withdraws.cashouts'))
  end

  def set_withdraw
    @withdraw_params = params[:agent_withdraw] || {}
    @withdraw = AgentWithdrawForm::Cashout.new(@withdraw_params.merge(level_cd: current_agent.agent_level_cd + 1))
  end

  def withdraw_params
    params.require(:agent_withdraw).permit(:username, :points, :note)
  end

  def valid_permission!
    authorize :withdraw, :agent?
  end
end

app/controllers/withdraw/agent_deposits_controller.rb
class Withdraw::AgentDepositsController < Withdraw::BaseController
  before_action :set_withdraw
  autocomplete :agent, :username
  # GET /agent_withdraw/:deposits/new
  def new; end

  def create
    if @withdraw.deposit
      @withdraw.agent.create_log(:deposit, current_agent, remote_ip ,points: @withdraw.points, agent_withdraw_id: @withdraw.model.id, trade_no: @withdraw.model.trade_no, status: 'transferred')
      unless @withdraw.agent.parent.nil?
        @withdraw.agent.parent.create_log(:deduct, current_agent, remote_ip ,points: @withdraw.points.to_f, agent_withdraw_id: @withdraw.cashout_model.id, trade_no: @withdraw.cashout_model.trade_no, status: 'transferred', related_agent_withdraw_id: @withdraw.model.id)
      end
      redirect_to new_withdraw_agent_deposit_path, notice: t('flash.agent_withdraw.deposits.finish')
    else
      render :new
    end
  end

  def autocomplete_agent_username
    term = params[:term]
    agents = current_agent.children.where('username LIKE ?', "%#{term}%").where(type_cd: 1).order(:username).all
    render :json => agents.map { |agent| {:id => agent.id, :label => agent.username, :value => agent.username} }
  end

  protected

  def set_breadcrumbs
    drop_breadcrumb(t('breadcrumbs.agent_withdraws.deposits'))
  end

  def set_withdraw
    @withdraw_params = params[:agent_withdraw] || {}
    @withdraw = AgentWithdrawForm::Deposit.new(@withdraw_params.merge(level_cd: current_agent.agent_level_cd + 1))
  end

  def withdraw_params
    params.require(:agent_withdraw).permit(:username, :points, :note)
  end

  def valid_permission!
    authorize :withdraw, :agent?
  end
end

app/controllers/withdraw/agent_withdraws_controller.rb
class Withdraw::AgentWithdrawsController < Withdraw::BaseController
  before_action :set_withdraw_type

  def index
    agent = @agent_id.to_i == 0 ? current_agent : current_agent.descendants.find(params[:id])
    drop_breadcrumb(agent.system_id)
    @withdraws = agent.agent_withdraws.search(params[:query]).withdraw_type(params[:type]).page(params[:page])
  end
  
  def show
    @withdraw = current_agent.descendants.find(params[:agent_id]).agent_withdraws.includes(:agent).find(params[:id])
  end

  protected

  def set_breadcrumbs
    drop_breadcrumb(t("breadcrumbs.withdraws.agent_withdraws"), withdraw_agent_withdraws_path)
  end

  def set_withdraw_type
    @agent_id = params[:id]
    @type = params[:type]
  end

  def valid_permission!
    authorize :withdraws, :agent?
  end
end

app/controllers/withdraw/base_controller.rb
class Withdraw::BaseController < ApplicationController
  before_action :valid_permission!, :set_breadcrumbs

  protected

  def valid_permission!
    authorize :withdraw, :agent?
  end
end

app/controllers/withdraws_controller.rb
# 玩家提款處理
class WithdrawsController < ApplicationController
  before_action :set_withdraw, except: :index
  before_action :set_breadcrumbs_path, :valid_permission!

  def index
    if params[:status].nil? || params[:status] == 'all'
      @withdraws = current_agent.withdraws.list_by_agent.search(params[:query]).page(params[:page])
    else
      @withdraws = current_agent.withdraws.list_by_agent.send("list_#{params[:status]}").search(params[:query]).page(params[:page])
    end
    @withdarw_count = current_agent.withdraws.list_by_agent.search(params[:query]).group(:status).count
  end

  # PUT /withdarws/1
  def update
    state = if params[:status] == 'transferred'
      # @withdraw.user.create_log("cashout", current_account, remote_ip ,credit: @withdraw.credit_actual, withdraw_id: @withdraw.id)
      @withdraw.finish!
      send_message(title: I18n.t("messages.withdraw.transferred.title"), content: I18n.t("messages.withdraw.transferred.content_html", link: "/account/withdraws/#{@withdraw.order_id}", order_id: @withdraw.order_id, credit: @withdraw.credit_actual), username: @withdraw.user.username, groups: [])
    elsif params[:status] == 'proccessing'
      @withdraw.proccess!
      send_message(title: I18n.t("messages.withdraw.proccessing.title"), content: I18n.t("messages.withdraw.proccessing.content_html", link: "/account/withdraws/#{@withdraw.order_id}", order_id: @withdraw.order_id, credit: @withdraw.credit), username: @withdraw.user.username, groups: [])
    else
      false
    end
    redirect_url(state, params[:status])
  end

  def destroy
    state = if params[:status] == 'removed'
      @withdraw.remove!
      send_message(title: I18n.t("messages.withdraw.removed.title"), content: I18n.t("messages.withdraw.removed.content_html", link: "/account/withdraws/#{@withdraw.order_id}", order_id: @withdraw.order_id, credit: @withdraw.credit), username: @withdraw.user.username, groups: [])
    elsif params[:status] == 'rejected'
      # @TODO 目前沒用到這個功能
      @withdraw.reject!
    else
      false
    end
    redirect_url(state, params[:status])
  end

  def show; end

  protected

  def set_breadcrumbs_path
    drop_breadcrumb(t('breadcrumbs.withdraws.handle_cashout'), withdraws_path)
  end

  def set_withdraw
    @withdraw = current_agent.withdraws.list_by_agent.find(params[:id])
  end

  def valid_permission!
    authorize :withdraw, :all?
  end

  def redirect_url(state, status)
    # save log
    @withdraw.user.create_log('cashout', current_account, remote_ip, status: status, credit: @withdraw.credit_actual.to_f, id: @withdraw.trade_no)

    if state
      redirect_to withdraws_url(status: status), notice: t("flash.withdraw.#{status}")
    else
      redirect_to withdraws_url(status: status), alert: t("flash.withdraw.#{status}_faild")
    end
  end
end

app/views/withdraw/agent_withdraws/_filter_bar.html.haml
%ul.nav
  .pull-right
    / filter bar
    %ul{class: 'nav nav-pills pull-left push-right-xs'}
      %li= nav_link(t('.all'), withdraw_agent_withdraws_path(type: 'all', id: @agent_id), class: 'hidden-sm hidden-xs')
      %li= nav_link(t('.deposit'), withdraw_agent_withdraws_path(type: 'deposit', id: @agent_id), class: 'hidden-sm hidden-xs')
      %li= nav_link(t('.cashout'), withdraw_agent_withdraws_path(type: 'cashout', id: @agent_id), class: 'hidden-sm hidden-xs')
      %li= nav_link(t('.refund'), withdraw_agent_withdraws_path(type: 'refund', id: @agent_id), class: 'hidden-sm hidden-xs')
      %li= nav_link(t('.deduct'), withdraw_agent_withdraws_path(type: 'deduct', id: @agent_id), class: 'hidden-sm hidden-xs')
  / search form
  -# = search_form_type(:query, params[:query], withdraw_agent_withdraws_path, type, placeholder: t('.search_placeholder'))
.push-xs

app/views/withdraw/agent_withdraws/_withdraw.html.haml
- cache [withdraw] do
  = content_tag_for(:tr, withdraw) do
    %td{data: {th: t('.id')}}= withdraw.trade_no
    %td{data: {th: t('.type')}}
      %span{class: "label label-#{withdraw.cash_type}"}= t("activerecord.enums.agent_withdraw.cash_types.#{withdraw.cash_type}")
    %td.right{data: {th: t('.points')}}= default_currency(withdraw.points)
    %td{data: {th: t('.note')}}= withdraw.note
    %td.right{data: {th: t('.update_time')}}= default_log_time(withdraw.updated_at)
    -# %td.center= link_to(t('btn.view'), withdraw_agent_withdraw_path(withdraw))

app/views/withdraw/agent_withdraws/index.html.haml
.alert.alert-warning
  = t('.current_points')
  %b= current_agent.points
= render('filter_bar', type: @type)
.table-rwd
  %table.table.table-valign-middle.table-font-sm.table-hover
    %thead
      %tr.success
        %th{width: 60}= t('.id')
        %th{width: 50}= t('.type')
        %th.right{width: 80}= t('.points')
        %th{width: 120}= t('.note')
        %th.right{width: 200}= t('.updated_at')
        -# %th.center{width: 50}
    %tbody
      - if @withdraws.empty?
        %tr
          %td{colspan: 5}= t('shared.no_data')
      = render partial: 'withdraw', collection: @withdraws, locals: {type: @type}
= will_paginate(@withdraws)

app/views/withdraw/agent_withdraws/show.html.haml
.row
  .col-md-8.col-md-offset-2
    %h3= t(".#{@withdraw.cash_type}.title")
    %ul.list-group
      %li.list-group-item
        %strong= @withdraw.agent.human_agent_level
        = link_to(@withdraw.agent.username, @withdraw.agent, class: 'font-gary')
      %li.list-group-item
        %strong= t('.nickname')
        = @withdraw.agent.nickname
      %li.list-group-item
        %strong= t('.cash_type_cd')
        %span{class: "label label-#{@withdraw.cash_type}"}= t("activerecord.enums.agent_withdraw.cash_types.#{@withdraw.cash_type}")
      %li.list-group-item
        %strong= t('.points')
        %strong.font-success= default_currency(@withdraw.points)
      %li.list-group-item
        %strong= t('.updated_at')
        %strong.font-success= default_log_time(@withdraw.updated_at)
      %li.list-group-item
        %strong= t('.note')
        = @withdraw.note
    - if @withdraw.bank_id.present?
      %h3= t('.title_account')
      %ul.list-group
        %li.list-group-item
          %strong= BankAccount.human_attribute_name(:bank_id)
          = t("bank_accounts.bank_title.#{@withdraw.bank_id}")
        %li.list-group-item
          %strong= BankAccount.human_attribute_name(:city)
          = @withdraw.city
        %li.list-group-item
          %strong= BankAccount.human_attribute_name(:province)
          = @withdraw.province
        %li.list-group-item
          %strong= BankAccount.human_attribute_name(:subbranch)
          = @withdraw.subbranch
        %li.list-group-item
          %strong= BankAccount.human_attribute_name(:account)
          = @withdraw.account